name: Run Tox
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            tox: py37
          - python-version: 3.8
            tox: py38
          - python-version: 3.9
            tox: py39
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tox
        env:
          TOXENV: ${{ matrix.tox }}
        run: tox

